# Use the official Node.js runtime as the base image
FROM node:18 AS build

# Set a default value for FRONTEND_INTERNAL_PORT
ARG FRONTEND_INTERNAL_PORT=5173

# URL for making REST API calls
ENV VITE_API_URL=http://localhost:8080/api

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Expose the default Vite port
EXPOSE ${FRONTEND_INTERNAL_PORT}

# Start the development server
CMD ["npm", "run", "dev"]
